# Generated by Django 3.2.25 on 2024-07-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_data_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='none.png', upload_to=''),
        ),
    ]
